2024-10-27 22:44:57,348 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\endovitskiy.a\PycharmProjects\pythonProject4\MODULE_12\tests_12_4.py", line 26, in test_run
    runner = Runner(3.14)
             ^^^^^^^^^^^^
  File "C:\Users\endovitskiy.a\PycharmProjects\pythonProject4\MODULE_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано float
2024-10-27 22:44:57,352 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\endovitskiy.a\PycharmProjects\pythonProject4\MODULE_12\tests_12_4.py", line 14, in test_walk
    Runner("name", -1)
  File "C:\Users\endovitskiy.a\PycharmProjects\pythonProject4\MODULE_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
